import BlankProvider from './provider/BlankProvider';
import injectProvider from './utils/inject';
import {
    Origin,
    WindowTransportResponseMessage,
} from '@blank/background/utils/types/communication';
import log, { LogLevelDesc } from 'loglevel';

// Setting the default log level:
/*
| 'trace'
| 'debug'
| 'info'
| 'warn'
| 'error'
| 'silent'
*/
log.setLevel((process.env.LOG_LEVEL as LogLevelDesc) || 'error');

const blankProvider = new BlankProvider();

// Listens to events generated by the background script
window.addEventListener(
    'message',
    ({ data, source }: MessageEvent<WindowTransportResponseMessage>): void => {
        // Only allow messages from our window, by the loader
        if (source !== window || data.origin !== Origin.BACKGROUND) {
            return;
        }

        if (data.id) {
            blankProvider.handleResponse(data);
        } else {
            log.error('Missing id for the response.');
        }
    }
);

const provider = new Proxy(blankProvider, {
    deleteProperty: () => true,
});

injectProvider(provider);
