name: Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag version"
        required: true
      commit:
        description: "Commit hash"
        required: false
      message:
        description: "Tag Message"
        required: false

jobs:
  tag:
    if: github.event.pull_request.merged == true || github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted
    environment:
      name: Testnet

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_RELEASE_BUCKET }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_RELEASE_BUCKET }}
          aws-region: us-east-2

      - run: echo "::set-output name=name::${{ github.event.inputs.tag }}_provider_release.zip"
        id: zip

      - run: echo "::set-output name=object::$(aws s3 ls s3://releases.goblank.io/provider/master --recursive | sort | tail -n 1 | awk '{print $4}')"
        id: s3-release

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - uses: fregante/setup-git-user@v1

      - name: Tag commit
        run: git tag -a ${{ github.event.inputs.tag }} ${{ github.event.inputs.commit }} -m "${{ github.event.inputs.message }}"

      - name: Push tags
        run: git push --tags

      - name: Slack notification - CI status
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

      - name: Slack notification - CI status
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "#00F6FA",
                  "pretext": "<http://releases.goblank.io/${{ steps.s3-release.outputs.object }}|Download> ${{ github.event.inputs.tag }} build release",
                  "author_name": "Provider ${{ github.event.inputs.tag }}",
                  "author_link": "https://github.com/Blank-Wallet/extension-provider",
                  "title": "Tag ${{ github.event.inputs.tag }} has been created in provider"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_RELEASES }}
